# Generated by Django 5.1.3 on 2024-12-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]
    operations = [
            migrations.AddField(
            model_name='file',
            name='encrypted_content',
            field=models.BinaryField(default=b''),
        ),
    ]
