# Generated by Django 5.1.4 on 2024-12-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_directoryshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectoryShare',
        ),
    ]
