# Generated by Django 5.1.4 on 2024-12-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_repository_file_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='repository',
        ),
    ]
