# Generated by Django 5.1.4 on 2024-12-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_file_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.repository'),
        ),
    ]
