# Generated by Django 5.1.4 on 2024-12-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_directory_created_at_directory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
