# Generated by Django 5.1.4 on 2024-12-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_file_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
