# Generated by Django 5.1.4 on 2024-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_customuser_private_key_customuser_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
