# Generated by Django 5.1.4 on 2024-12-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_customuser_token_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='file',
            name='signature',
        ),
    ]
